### ISSUE TITLE
Error File Not Found

### ISSUE THREAD

**Issue by jeremyworger** [ModuleArt/ferny#3]
Hi, just downloaded and installed Ferny.  
Im receiving this message when opening Ferny and when I open any new tab. 
-I'm not directed to the homepage (google) when I open Ferny.  
https://imgur.com/a/g9drlIo

**Comment by Beelink** [comment]
Hey. This has already been fixed in the new version.

**Comment by jeremyworger** [comment]
Hmm, im still getting the same error with v2.1...im assuming this is the new version?

**Comment by Beelink** [comment]
Sorry, I’m talking about a new version that has not yet been released.

**Comment by Beelink** [comment]
Wait for 3.0 (at the end of this month). Thanks

**Comment by jeremyworger** [comment]
Great, sounds good!
